version: '3'
services:
  # next-frontend:
  #   build: ./frontend
  #   image: next-frontend
  #   container_name: next-frontend
  #   ports:
  #     - 127.0.0.1:3000:3000
  #   depends_on:
  #     - strapi
  strapi-cms:
    build: ./cms
    image: project_cold_way_strapi-cms
    container_name: project_cold_way_strapi-cms
    ports:
      - 127.0.0.1:1337:1337
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: project_cold_way
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on: 
      - postgres

  postgres:
    image: postgres:12
    container_name: project_cold_way_postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres-strapidb-cold-way:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d/
    ports:
      - 127.0.0.1:15432:5432
volumes:
  postgres-strapidb-cold-way:
      driver: local