version: '3'
services:
  next-frontend:
    build: ./frontend
    image: project_cold_way_next-frontend
    container_name: project_cold_way_next-frontend
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./frontend/:/src/
      - /src/node_modules
    depends_on:
      - strapi-cms

  strapi-cms:
    build: ./cms
    image: project_cold_way_strapi-cms
    container_name: project_cold_way_strapi-cms
    ports:
      - 127.0.0.1:1337:1337
    volumes:
      - ./cms/:/srv/app
      - /srv/app/node_modules
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT:-postgres}
      DATABASE_NAME: ${DATABASE_NAME:-strapi}
      DATABASE_HOST: ${DATABASE_HOST:-postgres}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    depends_on: 
      - postgres

  postgres:
    image: postgres:12
    container_name: project_cold_way_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres-strapidb-cold-way:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d/
    ports:
      - 127.0.0.1:15432:5432

  express-backend: 
    build: ./backend
    image: project_cold_way_express-backend
    container_name: project_cold_way_express-backend
    ports:
      - 127.0.0.1:4000:4000
    volumes:
      - ./backend/:/src/
      - /src/node_modules

volumes:
  postgres-strapidb-cold-way:
      driver: local