FROM node:alpine

ENV NODE_ENV development

RUN mkdir /src
WORKDIR /src

COPY . /src

# install node_modules !: this requires  - /src/node_modules Volumne to have them seperate from main volume and not shared with host
RUN yarn
RUN yarn env:docker
RUN yarn build

# Running the app | start for prod | dev for development
EXPOSE 4000
CMD "yarn" "dev"