FROM ubuntu:bionic as build_packages
ENTRYPOINT ["/bin/bash"]

RUN mkdir /src
WORKDIR /src
COPY . /src

#? Setup
RUN chmod u+x ./janus.sh
RUN ./janus.sh setup

#? janus-gateway build
RUN ./janus.sh build


# Put configs in place
# COPY conf/*.jcfg /opt/janus/etc/janus/

# Running the app | start for prod | dev for development
EXPOSE 80 7088 8088 8188 10000-10200/udp
USER janus
CMD ["./janus.sh", "start"]